flowchart LR
  GH["GitHub CSVs"]
  SQL[("SQL DB")]
  ADF["Azure Data Factory"]
  ADLSB["ADLS Gen2 - Bronze"]
  DBS["Databricks - Silver"]
  DBG["Databricks - Gold"]
  SYN["Synapse Analytics"]
  PBI["Power BI Dashboards"]

  GH --> ADF
  SQL --> ADF
  ADF --> ADLSB
  ADLSB --> DBS
  DBS --> DBG
  DBG --> SYN
  DBG --> PBI


